### PR TITLE
Icon:  Add a SVG icon (#4)

### PR DESCRIPTION
**Pull request by leamas**
I have had a bad feeling about the overall SVG handling in the templates. So, took this opportunity to check things out, make a PR against you and an update of the wxsvg library (which was a complete mess). As a bonus, I have actually made an icon using inkscape, new tool to me.

Builds OK on all platforms, tested on flatpak which looks fine.

There is an overall need to communicate with the GUI code, in this case to get the correct size for the icon.  However, this is a separate issue, for now the size is hardcoded. Should be OK on most computers, but might fail miserably on high DPI screens and also on small Android devices. It's not worse than current situation, though.

### CODE REVIEW

**Comment by Hakansv** [comment]
192 new files to create one icon. It costs to be on top! 💯

**Comment by leamas** [comment]
It's really about _ocpn_plugin.h_. Enabling `ocpnUSE_SVG`  means that ocpn_plugin.h includes _wxSVG/svg.h_.  And that file pulls in the others. It's all in the wxsvg library.

That said, I agree. The way ocpn_plugin.h is coded is not nice here (or anywhere else, BTW).

**Comment by Hakansv** [comment]
The new icon on RPi 7" screen. Not bad!
bild

**Comment by leamas** [comment]
Indeed, not bad at all :)

EDIT: hm... it was such a long time ago I tinkered with this GUI. But it might be that the GUI rescales the icon to fit the pane... will need to check, later.

**Pull request merged**
